spring:
  security:
    user:
      name: mabrouka
      password: annabi
  application:
      name: Email_Service
eureka :
  instance:
   client:
    serviceUrl:
     defaultZone: http://localhost:8761/




#  Server configuration
server:
  port: 8086
